config/routes.rb
Rails.application.routes.draw do
  root 'gossips#index'
  devise_for :users
  resources :gossips
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :gossips

  before_validation :promocode

  def promocode
    codes = ["123CESTNOEL","METROPROMO","POURRILAND","#BALANCETONPOTE"]
    unless codes.include? codepromo
      errors.add :codepromo, "#{codepromo} is not on our Promotion list"  
  #    redirect_to new_user_registration_path
    end
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :sanitize_devise_params, if: :devise_controller?
  def sanitize_devise_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :codepromo])
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def index
    @gossips = Gossip.all
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = current_user.gossips.create(gossip_params)
    redirect_to root_path
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def show
    @gossip = Gossip.find(params[:id])
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to root_path
  end
private
  def gossip_params
    params.permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = []
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gossips/edit.html.erb
<h1>Gossips#edit</h1>
<p>Find me in app/views/gossips/edit.html.erb</p>

app/views/gossips/index.html.erb
<% if user_signed_in? %>
  <% @gossips.each do |goss| %>
    <p>
    <%= goss.created_at %>
    <%= User.find(goss.user_id).email %>
    </p>
    <p>
    <%= User.find(goss.user_id).username %>
    :..:Say:.....:
    <%= goss.content %>
    <% if goss.user_id == current_user.id %>
      <%= link_to 'Destroy', gossip_path(goss),
                   method: :delete,
                   data: { confirm: 'Are you sure?' } %>
    <% end %>
    </p>
    <br/>
  <% end %>
<% else %>
  <p>You need to login for have access to this site.</p>
<% end %>

app/views/gossips/new.html.erb
<%= form_tag("/gossips", method: "post") do %>
  <%= label_tag(:content, "Content:") %>
  <%= text_field_tag(:content) %>
  <%= submit_tag("Submit") %>
<% end %>

app/views/gossips/show.html.erb
<h1>Gossips#show</h1>
<p>Find me in app/views/gossips/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Devisetest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<% if user_signed_in? %>
<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
<%= link_to "Edit Profile", edit_user_registration_path %>
<%= link_to "New Gossip", new_gossip_path %>
<% else %>
<%= link_to "Sign In", new_user_session_path %>
<%= link_to "Sign Up", new_user_registration_path %>
<% end %>
<br/>

app/views/users/index.html.erb
<h1>YO! C'est l'index.</h1>
<% @users.each do |user| %>
<p> <%= user.email %> </p>
<% end %>